### ISSUE TITLE
Hello, where is the code for Locality Aware Appearance Metric

### ISSUE THREAD

**Issue by gyc521zsc** [hou-yz/open-reid-tracking#10]
![image](https://user-images.githubusercontent.com/50411057/85289239-ae110a80-b4c9-11ea-8947-d22ea00c9d62.png)

**Comment by hou-yz** [comment]
Thank you for your interest. I forgot to release it and will add it soon.

**Comment by gyc521zsc** [comment]
Thank you very much for your replyand look forward to your modification

**Comment by hou-yz** [comment]
It turns out that I have already released the metric network at [hou-yz/DeepCC-local](https://github.com/hou-yz/DeepCC-local/tree/master/src/hyper_score). Please go to that repo for more details.

**Comment by gyc521zsc** [comment]
Thank you for your reply


| |
Try to become like
|
|
15769060194@163.com
|
签名由网易邮箱大师定制
On 6/23/2020 13:34，Yunzhong Hou<notifications@github.com> wrote：

It turns out that I have already released the metric network at hou-yz/DeepCC-local. Please go to that repo for more details.
