### ISSUE TITLE
Dataset for tracking_gt

### ISSUE THREAD

**Issue by linkinpark213** [hou-yz/open-reid-tracking#9]
Hi, thanks for this great work on the ReID&MTMCT!

I wanted to train a intra-camera metric using DukeMTMC, and found in your code `reid/datasets/dukemtmc.py` that there should be a folder `ALL_gt_bbox` in the dataset directory. I can't seem to find any script that generates the images in it. Could you tell me how it's created?

**Comment by hou-yz** [comment]
Hi, thank you for your feedback. 

DukeMTMC dataset is actually prepared in the [DeepCC](https://github.com/hou-yz/DeepCC-local) repo. Please find it at [link](https://github.com/hou-yz/DeepCC-local/blob/master/src/prepare_bbox/get_ALL_gt_bbox.m). 

Cheers,
Yunzhong
